apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: my-notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /api/v1/notifications/health
            port: 8888
          initialDelaySeconds: 150
          periodSeconds: 30
          failureThreshold: 20  # Number of failures before restarting the container
        livenessProbe:
          httpGet:
            path: /api/v1/notifications/health
            port: 8888
          initialDelaySeconds: 150
          periodSeconds: 30
          failureThreshold: 20  # Number of failures before restarting the container
