apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: watchlist-service
  template:
    metadata:
      labels:
        app: watchlist-service
    spec:
      containers:
      - name: watchlist-service
        image: my-watchlist-service:latest
        imagePullPolicy: Never  # TODO: To be removed, should pull the image from cloud instead of local
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /api/watchlist/health
            port: 8888
          initialDelaySeconds: 150
          periodSeconds: 30
          failureThreshold: 10  # Number of failures before restarting the container
        livenessProbe:
          httpGet:
            path: /api/watchlist/health
            port: 8888
          initialDelaySeconds: 150
          periodSeconds: 30
          failureThreshold: 10  # Number of failures before restarting the container
